### ISSUE TITLE
Update Korean translation 

### ISSUE THREAD

**Issue by TangoEnSkai** [TangoEnSkai/uber-go-style-guide-kr#8]
## To people who want to contribute

**We encourage you to create a PR proactively to support this.**
Otherwise, I am going to finish:
  - updating the contents up-to-date
  - improve Korean translation

## What

- update the Korean translation with the 
  - ~[recent update: 2020/06/10](https://github.com/uber-go/guide/blob/master/CHANGELOG.md#2020-06-10)~ 
  - ~[2020/04/19](https://github.com/uber-go/guide/blob/master/CHANGELOG.md#2021-04-19)~
  - ~[2022/03/30](https://github.com/uber-go/guide/blob/master/CHANGELOG.md#2022-03-30)~
  - ~[2022/10/18](https://github.com/uber-go/guide/blob/master/CHANGELOG.md#2022-10-18)~
  - ~[2021/11/16](https://github.com/uber-go/guide/blob/master/CHANGELOG.md#2021-11-16)~
  - ~[2021/11/12](https://github.com/uber-go/guide/blob/master/CHANGELOG.md#2021-11-12)~
  - ~[2021/04/19](https://github.com/uber-go/guide/blob/master/CHANGELOG.md#2021-04-19)~
  - ~[2021/03/15](https://github.com/uber-go/guide/blob/master/CHANGELOG.md#2021-03-15)~
  - ~[2023/05/09](https://github.com/uber-go/guide/blob/master/CHANGELOG.md#2023-05-09)~
  - ~[2023/04/13](https://github.com/uber-go/guide/blob/master/CHANGELOG.md#2023-04-13)~
- ~all new updates that have not been updated yet in Korean~

## Why

- the main [recent update: 2020/06/10](https://github.com/uber-go/guide/blob/master/CHANGELOG.md#2020-06-10) has been merged into master
- current translation is not aligned with the latest doc

## TODO

update these topics:

- [x] Introduction: #13
- [x] Guidelines: #32 #33 #34 #35
- [x] Pointers to Interfaces: #14 
- [x] Verify Interface Compliance: #15 
- [x] Receivers and Interfaces: #16 
- [x] Zero-value Mutexes are Valid #17
- [x] Copy Slices and Maps at Boundaries #18
- [x] Defer to Clean Up #19
- [x] Channel Size is One or None #20
- [x] Start Enums at One #21
- [x] Use "time" to handle time #20
- [x] Error Types: #32
- [x] Error Wrapping: #32
- [x] Error Naming: #32
- [x] Handle Errors Once: #32
- [x] Handle Type Assertion Failures #21
- [x] Don't Panic #21
- [x] Use go.uber.org/atomic #21
- [x] Avoid Mutable Globals #21
- [x] Avoid Embedding Types in Public Structs #21
- [x] Avoid Using Built-In Names #21
- [x] Avoid init() #21
- [x] Exit in Main: #33
- [x] Exit Once: #33
- [x] Use field tags in marshaled structs: #34
- [x] Don't fire-and-forget goroutines: #35
- [x] Wait for goroutines to exit: #35
- [x] No goroutines in init(): #35
- [x] Performance
- [x] Prefer strconv over fmt #21
- [x] Avoid string-to-byte conversion #21
- [x] Prefer Specifying Container Capacity: #36
- [x] Specifying Map Capacity Hints: #36
- [x] Specifying Slice Capacity: #36
- [x] Style
- [x] Avoid overly long lines: #37
- [x] Be Consistent: #37
- [x] Group Similar Declarations #22
- [x] Import Group Ordering #22
- [x] Package Names #22
- [x] Function Names #22
- [x] Import Aliasing #22
- [x] Function Grouping and Ordering #22
- [x] Reduce Nesting #22
- [x] Unnecessary Else #22
- [x] Top-level Variable Declarations #22
- [x] Prefix Unexported Globals with _ #22
- [x] Embedding in Structs #22
- [x] Local Variable Declarations #22
- [x] nil is a valid slice #22
- [x] Reduce Scope of Variables #22
- [x] Avoid Naked Parameters #22
- [x] Use Raw String Literals to Avoid Escaping #22
- [x] Initializing Structs: #38
- [x] Use Field Names to Initialize Structs: #38
- [x] Omit Zero Value Fields in Structs: #38
- [x] Use var for Zero Value Structs: #38
- [x] Initializing Struct References: #42
- [x] Initializing Maps: #37
- [x] Format Strings outside Printf #22
- [x] Naming Printf-style Functions #22
- [x] Patterns
- [x] Test Tables #22
- [x] Avoid Unnecessary Complexity in Table Tests: #39
- [x] Parallel Tests: #39
- [x] Functional Options #22
- [x] Linting: #40
- [x] Lint Runners: #40

**Comment by Yupjun** [comment]
@TangoEnSkai Do you have any plan to update those? I want to contribute to the golang translation.

**Comment by TangoEnSkai** [comment]
> @TangoEnSkai Do you have any plan to update those? I want to contribute to the golang translation.

@Yupjun sorry for my late reply. I had a very long vacation.

Sure, you can create a PR for these.

I am actually thinking about restarting this issue in this month. 
Let me know if you want to contribute, and which part you want to do. 

**also, let me update this issue with the latest release since the target content `[2020/04/19](https://github.com/uber-go/guide/blob/master/CHANGELOG.md#2021-04-19)` seems out of date.

We can aim for the latest version: https://github.com/uber-go/guide/blob/master/CHANGELOG.md#2022-03-30

**Comment by TangoEnSkai** [comment]
## 완료 ✅

이 이슈에서 추적하던 모든 번역 작업이 완료되었습니다.

**완료된 PR 목록:**
- #32: Errors 섹션 구조 재편 + Error Naming, Handle Errors Once
- #33: Exit in Main + Exit Once
- #34: Use field tags in marshaled structs
- #35: Don't fire-and-forget goroutines
- #36: Prefer Specifying Container Capacity
- #37: Avoid overly long lines, Be Consistent, Initializing Maps
- #38: Initializing Structs 서브섹션 보완
- #39: Test Tables 서브섹션 보완 (Avoid Unnecessary Complexity, Parallel Tests)
- #40: Linting 섹션 전체
- #41: 위 내용 master 반영
- #42: 구조체 참조 초기화 섹션 위치 수정

현재 master의 한국어 번역이 원문과 구조적으로 완전히 일치합니다.
